// <auto-generated />
using System;
using Gatocan.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gatocan.Data.Migrations
{
    [DbContext(typeof(GatocanContext))]
    [Migration("20250520201344_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Gatocan.Model.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2024, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Gatocan.Model.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CartId = 1,
                            ProductId = 2,
                            Quantity = 3
                        });
                });

            modelBuilder.Entity("Gatocan.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("longDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Royal Canin",
                            Category = "Alimentación",
                            Description = "Pienso para perros adultos de razas grandes que minimiza los efectos del envejecimiento y mejora la salud articular.",
                            ImageUrl = "/images/products/royalcanin.jpg",
                            Name = "Royal Canin Maxi Adult pienso para perros",
                            Price = 20.5,
                            Stock = 50,
                            longDescription = "Royal Canin Maxi Adult es el alimento indicado para aquellos perros que en edad adulta alcanzan más de 25 kg gracias a su receta, creada especialmente para mantener su organismo en un estado óptimo."
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Advance",
                            Category = "Alimentación",
                            Description = "Pienso de pollo y arroz para perros medianos adultos.",
                            ImageUrl = "/images/products/advance.jpg",
                            Name = "Advance Active Defense Medium Adult Pollo y Arroz pienso para perros",
                            Price = 67.0,
                            Stock = 25,
                            longDescription = "Se trata de un alimento para perros especialmente diseñado para cubrir todas sus necesidades. Su composición cuenta con una destacada selección de proteínas e hidratos de carbono, lo que ayuda a mantener una digestibilidad muy alta y un correcto proceso digestivo. Además de pirofosfatos, un componente que evita el mal aliento y la formación de sarro."
                        },
                        new
                        {
                            Id = 3,
                            Brand = "True Origins",
                            Category = "Alimentación",
                            Description = "Comida húmeda de atún y sardinas para gatos adultos.",
                            ImageUrl = "/images/products/trueorigins.jpg",
                            Name = "True Origins Pure Adult Atún y Sardina lata para gatos",
                            Price = 18.699999999999999,
                            Stock = 45,
                            longDescription = "Este delicioso alimento complementario para gatos de la marca True Origins es adecuado para que tu mascota se mantenga fuerte y sana, además de disfrutar de un delicioso alimento húmedo con muchas vitaminas y minerales esenciales para su alimentación."
                        },
                        new
                        {
                            Id = 4,
                            Brand = "True Origins",
                            Category = "Alimentación",
                            Description = "Snack totalmente natural sin cereales ni azúcares para gatos adultos.",
                            ImageUrl = "/images/products/trueorigins2.jpg",
                            Name = "True Origins Pure Bocaditos Adult Crunchy de Pavo para gatos",
                            Price = 35.799999999999997,
                            Stock = 50,
                            longDescription = "Los bocaditos para gatos Pure Crunchy de True Origins son ideales para ofrecer a tu felino adulto una golosina deliciosa en cualquier momento del día para recompensarle o mimarle, de esta forma, complementarás su dieta de manera óptima y saludable. Cuentan con una fórmula deliciosa que mezcla carne fresca de pavo con vegetales, junto a una textura crujiente única que a tu mascota le encantará masticar a cualquier hora."
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Royal Canin",
                            Category = "Alimentación",
                            Description = "Alimento húmedo sano y equilibrado para gatos seniors.",
                            ImageUrl = "/images/products/royalcanin2.jpg",
                            Name = "Royal Canin Ageing 12+ sobre en salsa para gatos",
                            Price = 10.0,
                            Stock = 40,
                            longDescription = "Los sobres de comida húmeda Royal Canin Ageing cuidan la salud de los gatos de edad avanzada, ya que se adaptan completamente a sus necesidades y evita el riesgo de que puedan padecer algunas enfermedades como la insuficiencia renal o artrosis."
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Advance",
                            Category = "Alimentación",
                            Description = "Pienso para gatos esterilizados que pueden sufrir un aumento de peso. También ayuda a reducir la formación de bolas de pelo.",
                            ImageUrl = "/images/products/advance1.jpg",
                            Name = "Advance Sterilized Hairball Pavo y Cebada pienso para gatos",
                            Price = 49.0,
                            Stock = 20,
                            longDescription = "El pienso para gatos Advance Sterilized Hairball es perfecto para aquellos gatos que han pasado por una esterilización o una castración y que presentan o pueden presentar los problemas típicos de este tipo de intervenciones, como el aumento de peso."
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Flamingo",
                            Category = "Juguetes",
                            Description = "Caña para gatos Flamingo Happy Flower",
                            ImageUrl = "/images/products/flamingo.jpg",
                            Name = "Flamingo Happy Caña con flor para gatos",
                            Price = 4.0,
                            Stock = 60,
                            longDescription = "La caña para gatos Flamingo Happy Flower con flor de peluche es un original juguete interactivo que desarrolla la motivación y concentración de tu mascota y con el que pasará muchos gratos y divertidos momentos. Un llamativo accesorio con el que conseguirás que tu pequeño amigo peludo esté activo y realice el ejercicio diario necesario para estar saludable."
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Tootoy!",
                            Category = "Juguetes",
                            Description = "Pato de peluche para perros, con sonido y mordedor circular de cuerda, fabricado en tejido vaquero suave.",
                            ImageUrl = "/images/products/tootoy.jpg",
                            Name = "Tootoy! Comfort Denim Duck peluche con sonido y cuerda para perros",
                            Price = 15.0,
                            Stock = 25,
                            longDescription = "El peluche de pato de tejido vaquero de Tootoy! es se convertirá en el mejor amigo de tu perro. Su diseño adorable y su tejido vaquero suave lo convierten en el accesorio perfecto para dormir la siesta, mientras que el pitido que emite cuando lo muerden y el mordedor de cuerda circular que incorpora este juguete, les divierte y estimula su curiosidad. A tu perro le encantará este peluche ¿Quién le dice que ese pato nunca correrá ni volará para él?"
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Nylabone",
                            Category = "Juguetes",
                            Description = "Nylabone hueso mordedor de nylon para perros.",
                            ImageUrl = "/images/products/nylabone.jpg",
                            Name = "Nylabone Extreme Chew Pollo Hueso Mordedor para perros",
                            Price = 5.0,
                            Stock = 35,
                            longDescription = "Mordedor para perros de Nylabone diseñado para satisfacer los instintos naturales de tu mascota, evitando así que muerda muebles u otros objetos, además fortalece la mandíbula dándole un mejor agarre, también protege los dientes en cada mordida que le da al juguete, ya que limpia y evita la aparición de sarro. Este masticador para perros contiene un sabor delicioso y duradero a pollo, lo que hará que tu mascota pase mucho más tiempo jugando."
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Flamingo",
                            Category = "Juguetes",
                            Description = "El Calamar azul de Flamingo es un juguete para perros que posee termoplástico en la cabeza y a su vez de felpa que masajea las encías de tu mascota, previene el sarro y la placa.",
                            ImageUrl = "/images/products/flamingo1.jpg",
                            Name = "Flamingo Wilco Calamar Azul de Peluche para perros",
                            Price = 6.9000000000000004,
                            Stock = 32,
                            longDescription = "El divertido calamar azul de peluche para perros es un excelente juguete de Flamingo, pues es un artículo funcional para tu mascota. Por un lado, tu peludo amigo se entretendrá mordiendo la parte superior del peluche y por otro, debido a sus filamentos de termoplástico, se hará auto-limpieza dental para mantener una buena higiene bucodental. "
                        },
                        new
                        {
                            Id = 11,
                            Brand = "TK-Pet",
                            Category = "Higiene",
                            Description = "La bandeja sanitaria cerrada TK-Pet Minerva es un práctico aseo de color rojo para gatos de cualquier raza y tamaño, con el que hacen sus necesidades cómodamente.",
                            ImageUrl = "/images/products/tkpet.jpg",
                            Name = "TK-Pet Minerva Bandeja Sanitaria para gatos",
                            Price = 22.600000000000001,
                            Stock = 31,
                            longDescription = "Como sucede con los humanos, los animales también necesitan intimidad cuando se trata de hacer sus necesidades. Por ello, TK Pet lanza al mercado la bandeja sanitaria cerrada Minerva para gatos, un accesorio agradable y amplio adecuado para felinos de todas las razas y tamaños."
                        },
                        new
                        {
                            Id = 12,
                            Brand = "Furminator",
                            Category = "Higiene",
                            Description = "Furminator cepillo para perros. Ideal para eliminar el pelo muerto de tu mascota de una forma fácil",
                            ImageUrl = "/images/products/furminator.jpg",
                            Name = "Furminator Cepillo para perros de pelo largo",
                            Price = 32.899999999999999,
                            Stock = 20,
                            longDescription = "No siempre es fácil mantener el mejor aspecto en tu mascota, sobre todo, si esta tiene un largo pelaje. Pero con el cepillo Furminator para perros estos problemas desaparecerán, ya que con él podrás eliminar el pelo muerto de tu mascota de forma más sencilla. Este accesorio está diseñado para perros de largo pelaje, ya que elimina el pelo muerto de la mascota y ayuda a la producción de aceites naturales y a conseguir una piel más sana."
                        },
                        new
                        {
                            Id = 13,
                            Brand = "PSH",
                            Category = "Higiene",
                            Description = "Champú para perros y gatos, indicado para pieles sensibles, con irritaciones o intolerancias dérmicas",
                            ImageUrl = "/images/products/psh.jpg",
                            Name = "PSH Sensitive Skin Champú para perros y gatos",
                            Price = 15.9,
                            Stock = 60,
                            longDescription = "Champú para perros y gatos, indicado para pieles sensibles, con irritaciones o intolerancias dérmicas, hidrata y humecta la piel, aporta suavidad y elasticidad, elimina impurezas."
                        });
                });

            modelBuilder.Entity("Gatocan.Model.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 20.5,
                            Date = new DateTime(2024, 5, 6, 0, 9, 2, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Tarjeta",
                            ProductId = 1,
                            Quantity = 1,
                            Tipo = 1,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Gatocan.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<double>("Balance")
                        .HasColumnType("float");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 100.0,
                            Email = "juan@example.com",
                            Lastname = "Pérez",
                            Name = "Juan",
                            Password = "pass123",
                            Role = "user"
                        },
                        new
                        {
                            Id = 2,
                            Balance = 150.0,
                            Email = "albertoriveiro@hotmail.es",
                            Lastname = "Riveiro",
                            Name = "Alberto",
                            Password = "pass456",
                            Role = "admin"
                        });
                });

            modelBuilder.Entity("Gatocan.Model.Cart", b =>
                {
                    b.HasOne("Gatocan.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gatocan.Model.CartItem", b =>
                {
                    b.HasOne("Gatocan.Model.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gatocan.Model.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Gatocan.Model.Transaction", b =>
                {
                    b.HasOne("Gatocan.Model.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Gatocan.Model.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gatocan.Model.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Gatocan.Model.User", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
